version: '3.8'
services:
  jenkins:
    image: jenkins/jenkins:2.402-jdk11
    privileged: true
    restart: always
    user: root
    ports:
      - 1011:8080
      - 51011:50000
    container_name: jenkins
    volumes:
      - ./volumes:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/bin/docker-compose
    deploy:
      resources:
        limits:
          memory: 2048M
  sonarqube:
    image: sonarqube
    hostname: sonarqube
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - ./sonarqube/sonarqube_data:/opt/sonarqube/data
      - ./sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube/sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9001:9000"
  db:
    image: postgres:13
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - ./database/postgresql:/var/lib/postgresql
      - ./database/postgresql_data:/var/lib/postgresql/data
